export const SCAM_SIGNAL_RULES = [
  {
    id: "urgency-act-now",
    category: "Urgency",
    label: "Urgent pressure to act quickly",
    weight: 12,
    patterns: [
      /\bact now\b/i,
      /\burgent\b/i,
      /\bimmediately\b/i,
      /\blimited time\b/i,
      /\bwithin 24 hours\b/i,
      /\bexpires? today\b/i,
      /\bfinal warning\b/i,
      /\bavoid (?:a )?(?:fine|penalty|charge)\b/i,
    ],
    explanation:
      "Scams often create time pressure so people act before checking properly.",
  },
  {
    id: "money-pressure",
    category: "Money pressure",
    label: "Pressure to send money or unusual payment",
    weight: 18,
    patterns: [
      /\bsend money\b/i,
      /\bbank transfer\b/i,
      /\bwire transfer\b/i,
      /\bgift cards?\b/i,
      /\bcrypto(?:currency)?\b/i,
      /\bbitcoin\b/i,
      /\brefund fee\b/i,
      /\badmin fee\b/i,
      /\bprocessing fee\b/i,
      /\bsecurity deposit\b/i,
      /\bsmall fee\b/i,
      /\bpay(?:ment)? required\b/i,
    ],
    explanation:
      "Requests for fast or unusual payments are a common warning sign.",
  },
  {
    id: "credential-request",
    category: "Personal details",
    label: "Asks for passwords, PINs, or verification codes",
    weight: 22,
    patterns: [
      /\bpassword\b/i,
      /\bverification code\b/i,
      /\bone[- ]?time code\b/i,
      /\bOTP\b/i,
      /\bPIN\b/i,
      /\blogin details\b/i,
      /\bsecurity code\b/i,
      /\bconfirm your identity\b/i,
      /\bauthorisation code\b/i,
      /\bone[- ]?time password\b/i,
    ],
    explanation:
      "Real banks and services should not ask you to share passwords, PINs, or one-time codes by message.",
  },
  {
    id: "impersonation-known-org",
    category: "Impersonation",
    label: "Mentions a commonly impersonated organisation",
    weight: 10,
    patterns: [
      /\bHMRC\b/i,
      /\bbank\b/i,
      /\bRoyal Mail\b/i,
      /\bEvri\b/i,
      /\bDPD\b/i,
      /\bpolice\b/i,
      /\bMicrosoft support\b/i,
      /\bAmazon\b/i,
      /\bPayPal\b/i,
      /\bDVLA\b/i,
      /\bNHS\b/i,
      /\bTV Licensing\b/i,
      /\bEE\b/i,
      /\bO2\b/i,
    ],
    explanation:
      "Scammers often pretend to be trusted organisations.",
  },
  {
    id: "parcel-redelivery-fee",
    category: "Parcel scam",
    label: "Parcel redelivery fee request",
    weight: 22,
    patterns: [
      /\b(?:Royal Mail|Evri|DPD|parcel|delivery)\b.{0,80}\b(?:redelivery|re[- ]?delivery|reschedule|missed delivery)\b/i,
      /\b(?:parcel|package)\b.{0,80}\b(?:fee|charge|customs|postage)\b/i,
      /\b(?:pay|settle).{0,40}\b(?:parcel|delivery|redelivery)\b/i,
    ],
    explanation:
      "Fake parcel redelivery fee messages are a common UK scam pattern.",
  },
  {
    id: "hmrc-tax-refund",
    category: "Tax refund scam",
    label: "HMRC tax refund or rebate hook",
    weight: 22,
    patterns: [
      /\bHMRC\b.{0,80}\b(?:refund|rebate|tax return|overpaid|claim)\b/i,
      /\b(?:tax refund|tax rebate|refund pending|claim your refund)\b/i,
    ],
    explanation:
      "Unexpected tax refund messages should be checked through the official HMRC website, not message links.",
  },
  {
    id: "dvla-vehicle-scam",
    category: "DVLA scam",
    label: "DVLA vehicle tax or fine pressure",
    weight: 18,
    patterns: [
      /\bDVLA\b.{0,80}\b(?:vehicle tax|road tax|fine|penalty|refund|licence|license)\b/i,
      /\bvehicle tax\b.{0,80}\b(?:unpaid|overdue|fine|penalty)\b/i,
    ],
    explanation:
      "DVLA-themed payment or penalty messages are often used to push people into unsafe links.",
  },
  {
    id: "nhs-payment-scam",
    category: "NHS scam",
    label: "NHS appointment or payment request",
    weight: 16,
    patterns: [
      /\bNHS\b.{0,80}\b(?:payment|fee|refund|appointment|prescription|booking)\b/i,
      /\bmissed NHS appointment\b/i,
    ],
    explanation:
      "Unexpected NHS payment or appointment messages should be verified through official NHS routes.",
  },
  {
    id: "bank-otp-scam",
    category: "Bank code scam",
    label: "Bank verification code or OTP request",
    weight: 24,
    patterns: [
      /\bbank\b.{0,80}\b(?:OTP|verification code|security code|PIN|password)\b/i,
      /\b(?:OTP|verification code|security code)\b.{0,80}\b(?:reply|send|share|confirm)\b/i,
      /\bapprove this transaction\b/i,
    ],
    explanation:
      "Never share bank verification codes, OTPs, PINs, or passwords from a message.",
  },
  {
    id: "remote-access-support",
    category: "Remote access scam",
    label: "Remote access or fake support request",
    weight: 24,
    patterns: [
      /\bMicrosoft support\b/i,
      /\bWindows support\b/i,
      /\bremote access\b/i,
      /\bAnyDesk\b/i,
      /\bTeamViewer\b/i,
      /\binstall.{0,40}(?:support|security|remote)\b/i,
      /\byour computer has (?:a )?virus\b/i,
    ],
    explanation:
      "Fake support scams often ask people to install remote access tools or believe their device is infected.",
  },
  {
    id: "investment-crypto-pressure",
    category: "Investment scam",
    label: "Investment or crypto pressure",
    weight: 20,
    patterns: [
      /\bguaranteed returns?\b/i,
      /\bdouble your money\b/i,
      /\brisk[- ]?free investment\b/i,
      /\binvest now\b/i,
      /\bcrypto wallet\b/i,
      /\btrading platform\b/i,
      /\bexclusive opportunity\b/i,
    ],
    explanation:
      "Promises of guaranteed returns or pressure to invest quickly are common investment scam warning signs.",
  },
  {
    id: "emotional-manipulation",
    category: "Emotional pressure",
    label: "Emotional pressure or secrecy",
    weight: 18,
    patterns: [
      /\bfamily emergency\b/i,
      /\bI lost my phone\b/i,
      /\bnew number\b/i,
      /\bdon'?t tell anyone\b/i,
      /\bkeep this secret\b/i,
      /\bplease help me\b/i,
      /\bI need help urgently\b/i,
    ],
    explanation:
      "Messages that mix urgency, secrecy, and family pressure should be checked carefully.",
  },
  {
    id: "family-new-number",
    category: "Family message",
    label: "Family-style new number money request",
    weight: 24,
    patterns: [
      /\bhi mum\b/i,
      /\bhi dad\b/i,
      /\bnew number\b/i,
      /\blost my phone\b/i,
      /\bcan you pay\b/i,
      /\bplease transfer\b/i,
      /\bWhatsApp\b.{0,60}\bnew number\b/i,
    ],
    explanation:
      "Scammers often pretend to be a family member using a new phone number and then ask for money.",
  },
  {
    id: "prize-refund-hook",
    category: "Prize or refund hook",
    label: "Prize, refund, parcel fee, or tax rebate hook",
    weight: 16,
    patterns: [
      /\byou won\b/i,
      /\bwinner\b/i,
      /\brefund pending\b/i,
      /\bparcel fee\b/i,
      /\bdelivery fee\b/i,
      /\btax rebate\b/i,
      /\btax refund\b/i,
      /\bclaim your refund\b/i,
      /\bclaim now\b/i,
    ],
    explanation:
      "Prize, refund, delivery-fee, and rebate messages are common scam hooks.",
  },
  {
    id: "threat-or-penalty",
    category: "Threat",
    label: "Threat of penalty, arrest, closure, or blocked access",
    weight: 15,
    patterns: [
      /\baccount (?:will be )?(?:closed|blocked|suspended|locked)\b/i,
      /\blegal action\b/i,
      /\barrest\b/i,
      /\bfine\b/i,
      /\bpenalty\b/i,
      /\bdebt collection\b/i,
      /\bprosecution\b/i,
    ],
    explanation:
      "Threats are often used to rush people into unsafe actions.",
  },
];

export const SHORTENED_URL_DOMAINS = new Set([
  "bit.ly",
  "tinyurl.com",
  "t.co",
  "goo.gl",
  "ow.ly",
  "is.gd",
  "buff.ly",
  "cutt.ly",
  "shorturl.at",
  "rebrand.ly",
  "lnkd.in",
]);

export const SUSPICIOUS_DOMAIN_HINTS = [
  { pattern: /royal[-.]?mail[^/]*\.(?:top|xyz|click|info|shop|online|site)$/i, label: "Royal Mail lookalike domain" },
  { pattern: /(?:evri|dpd|parcel|delivery)[^/]*\.(?:top|xyz|click|info|shop|online|site)$/i, label: "Parcel delivery lookalike domain" },
  { pattern: /hmrc[^/]*\.(?:top|xyz|click|info|shop|online|site)$/i, label: "HMRC lookalike domain" },
  { pattern: /dvla[^/]*\.(?:top|xyz|click|info|shop|online|site)$/i, label: "DVLA lookalike domain" },
  { pattern: /nhs[^/]*\.(?:top|xyz|click|info|shop|online|site)$/i, label: "NHS lookalike domain" },
  { pattern: /paypa1|paypaI|royaI|micros0ft|arnazon|barc1ays|natvvest|hsbcsecure/i, label: "Possible misspelling of a trusted brand" },
  { pattern: /verify|secure|account|login|refund|parcel|rebate|redelivery|support|wallet/i, label: "Domain uses scam-like action words" },
];
